name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true      
      - run: | 
          xcodebuild \
            -project FlickrFindr.xcodeproj \
            -scheme FlickrFindr \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' \
            build \
            test
      # - uses: michaelhenry/swifty-code-coverage@v1.0.0
      #   with:
      #     build-path: DerivedData
      #     target: FlickrFindr.app
      #     is-spm: false
      - run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        # with:
          # files: ./cobertura.xml
          # functionalities: fixes
          # swift: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
